import Head from "next/head";
import Layout from "../components/Layout/index";
import Register from "../features/index.tsx";
export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Register />
      </Layout>
    </>
  );
}
